// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMOl6bCDCFpqEGtBeZri5yGLfkMQSVy28',
    appId: '1:643054187441:web:2fc0a479050307a4694390',
    messagingSenderId: '643054187441',
    projectId: 'my-notes-f97ea',
    authDomain: 'my-notes-f97ea.firebaseapp.com',
    storageBucket: 'my-notes-f97ea.firebasestorage.app',
    measurementId: 'G-V5NFP939WK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtStrOvAiPwyOMdKgdfJvJNWeNU09b2JY',
    appId: '1:643054187441:android:f58666ac51a65e5c694390',
    messagingSenderId: '643054187441',
    projectId: 'my-notes-f97ea',
    storageBucket: 'my-notes-f97ea.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANLmJzG97IItgXeCtGf2Z7plDgxSFTyvM',
    appId: '1:643054187441:ios:8d8a76d7a03a83ab694390',
    messagingSenderId: '643054187441',
    projectId: 'my-notes-f97ea',
    storageBucket: 'my-notes-f97ea.firebasestorage.app',
    iosBundleId: 'com.example.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANLmJzG97IItgXeCtGf2Z7plDgxSFTyvM',
    appId: '1:643054187441:ios:8d8a76d7a03a83ab694390',
    messagingSenderId: '643054187441',
    projectId: 'my-notes-f97ea',
    storageBucket: 'my-notes-f97ea.firebasestorage.app',
    iosBundleId: 'com.example.mynotes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCMOl6bCDCFpqEGtBeZri5yGLfkMQSVy28',
    appId: '1:643054187441:web:7b8fa0fd6199f845694390',
    messagingSenderId: '643054187441',
    projectId: 'my-notes-f97ea',
    authDomain: 'my-notes-f97ea.firebaseapp.com',
    storageBucket: 'my-notes-f97ea.firebasestorage.app',
    measurementId: 'G-1KRK3EHL1S',
  );
}
